name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_DB: test-postgres-query
          POSTGRES_PASSWORD: 2UtcMAAvNuBHPqK9
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace
      env:
        DATABASE_URL: postgresql://postgres:2UtcMAAvNuBHPqK9@localhost:5432/test-postgres-query
